package com.telegrambot.WildberriesBot.states;

public enum BotState {
    SHOW_HELP_MENU,
    SHOW_MAIN_MENU,
    SUBSCRIPTION_START,
    SUBSCRIPTION_PROCESS,
    UNSUBSCRIPTION_START,
    UNSUBSCRIPTION_PROCESS,
    SHOW_CART_LIST,
    NULL_STATE,
    PRICE_PROCESS
}
